In [1]:
print('으~~')

으~~


In [2]:
import cv2

In [6]:
# sudo apt-get install pkg-config
# pkg-config --modversion opencv
# sudo apt-get install build-essential cmake
# sudo apt-get install freeglut3 freeglut3-dev
# sudo apt-get install glew-utils glee-dev
# sudo apt-get install libglew-dev
# sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev
# sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libxvidcore-dev libx264-dev libxine2-dev
# sudo apt-get install libv4l-dev v4l-utils
# sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
# sudo apt-get install libgtk2.0-dev
# sudo apt-get install mesa-utils libgl1-mesa-dri libgtkgl2.0-dev libgtkglext1-dev
# sudo apt-get install libatlas-base-dev gfortran libeigen3-dev

In [7]:
# cd ~
# cd sw/
# mkdir opencv
# cd opencv
# wget -O opencv.zip https://github.com/opencv/opencv/archive/4.2.0.zip
# unzip opencv.zip

In [8]:
# wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.2.0.zip
# unzip opencv_contrib.zip

In [9]:
# cd opencv-4.2.0/
# mkdir build
# cd build

In [10]:
# 아나콘다 환경 설정 잠시 정지시킴
# sudo apt-get install python2.7-dev python3-dev python-numpy python3-numpy

In [11]:
# /home/bitai/anaconda3/bin/python

In [12]:
# 아나콘다 경로를 잘 파악하고 있다면 문제 없음
# cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local
-D WITH_TBB=OFF -D WITH_IPP=OFF -D WITH_1394=OFF -D BUILD_WITH_
DEBUG_INFO=OFF -D BUILD_DOCS=OFF -D INSTALL_C_EXAMPLES=ON -D INSTALL_
PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D 
BUILD_PERF_TESTS=OFF -D WITH_QT=OFF -D WITH_GTK=ON -D WITH_OPENGL=ON 
-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.2.0/modules -D 
WITH_V4L=ON -D WITH_FFMPEG=ON -D WITH_XINE=ON -D BUILD_NEW_PYTHON_
SUPPORT=ON -D OPENCV_GENERATE_PKGCONFIG=ON ../

SyntaxError: invalid syntax (<ipython-input-12-c4b21b83e925>, line 3)

In [ ]:
# 아나콘다상의 파이썬 경로를 파악하지 못한다면 아래 방식으로
# cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local
-D WITH_TBB=OFF -D WITH_IPP=OFF -D WITH_1394=OFF -D BUILD_WITH_
DEBUG_INFO=OFF -D BUILD_DOCS=OFF -D INSTALL_C_EXAMPLES=ON -D 
INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF 
-D BUILD_PERF_TESTS=OFF -D WITH_QT=OFF -D WITH_GTK=ON -D WITH_OPENGL=
ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.2.0/modules 
-D WITH_V4L=ON -D WITH_FFMPEG=ON -D WITH_XINE=ON -D BUILD_NEW_
PYTHON_SUPPORT=ON -D OPENCV_GENERATE_PKGCONFIG=ON -D PYTHON3_INCLUDE_
DIR=/home/bitai/anaconda3/include/python3.7m/ -D PYTHON3_NUMPY_INCLUDE
_DIRS=/home/bitai/anaconda3/lib/python3.7/site-packages/numpy/core/
include/ -D PYTHON3_PACKAGES_PATH=/home/bitai/anaconda3/lib/python3.7/
site-packages -D PYTHON3_LIBRARY=/home/bitai/anaconda3/lib/libpython3.
7m.so ../

In [13]:
# cat /proc/cpuinfo | grep processor | wc -l
# time make -j12

In [14]:
# sudo make install

In [15]:
# cat /etc/ld.so.conf.d/*
# sudo ldconfig

In [ ]:
# cd ~/proj/
# mkdir test
# cd test
# g++ -o facedetect /usr/local/share/opencv4/samples/cpp/
facedetect.cpp $(pkg-config opencv4 --libs --cflags)
# ./facedetect --cascade="/usr/local/share/opencv4/haarcascades/
haarcascade_frontalface_alt.xml" --nested-cascade="/usr/local/share/
opencv4/haarcascades/haarcascade_eye_tree_eyeglasses.xml" --scale=1.3

In [16]:
# 아나콘다 설정 다시 활성화

In [3]:
!pip install opencv-python

In [4]:
import cv2

In [5]:
print(cv2.__version__)

4.3.0


In [17]:
import numpy as np

In [18]:
img = np.random.randint(0, 10, (7, 7))

print(img)

[[2 0 6 4 7 5 3]
 [9 5 7 6 5 2 3]
 [9 7 9 4 0 1 0]
 [2 0 7 3 7 2 2]
 [1 2 5 6 8 9 1]
 [0 7 5 7 0 8 9]
 [7 5 4 1 6 3 3]]


In [19]:
img_np = np.ones([7, 7])

print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [33]:
kernel = np.array([-1, 0, 1])

print(kernel)

[-1  0  1]


In [34]:
print(type(kernel))
print(type(img_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [35]:
img_cv = cv2.resize(img_np, (7, 7))

print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [36]:
kernel = cv2.resize(kernel, (1, 3))

print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [37]:
print(type(img_cv))
print(type(kernel))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [38]:
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [39]:
print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [44]:
print(img_cv)

[[0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 3.]]


In [45]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3

# filter2D - Convolution이 결국 라플라스 변환과 
# 푸리에 변환에 관계를 가지고 있기 때문
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [46]:
# sudo apt-get install ctags cscope

In [1]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense
from keras.layers import Dropout

In [2]:
classifier = Sequential()
classifier.add(
    Conv2D(
        32, (3, 3), 
        input_shape = (64, 64, 3), 
        activation = 'relu'
    )
)
classifier.add(MaxPool2D(pool_size = (2, 2)))

classifier.add(Flatten())

In [3]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 30752)             0         
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [11]:
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(Dropout(0.2))
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(64, activation = 'relu')
)
classifier.add(
    Dense(64, activation = 'relu')
)
classifier.add(
    Dense(32, activation = 'relu')
)
classifier.add(
    Dense(16, activation = 'relu')
)
classifier.add(
    Dense(1, activation = 'sigmoid')
)

classifier.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [12]:
from keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    rescale = 1. / 255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)

test_gen = ImageDataGenerator(rescale = 1.0 / 255)

In [13]:
! ls Applied-Deep-Learning-with-Keras/Lesson07

Activity13.ipynb  Datasets	    Exercise20.ipynb  Exercise22.ipynb
Activity14.ipynb  Exercise19.ipynb  Exercise21.ipynb


In [14]:
! ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set

cats  dogs


In [15]:
trainSet = train_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/' +
    'Datasets/dataset/training_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)
testSet = test_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/' +
    'Datasets/dataset/test_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)

Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.


In [16]:
batch_size = 100

classifier.fit_generator(
    trainSet,
    steps_per_epoch = int(10000/batch_size),
    epochs = 100,
    validation_data = testSet,
    validation_steps = int(2500/batch_size)
)

Epoch 1/100
100/100 [==============================] - 9s 92ms/step - loss: 0.6435 - accuracy: 0.6422 - val_loss: 0.6013 - val_accuracy: 0.7088
Epoch 2/100
100/100 [==============================] - 9s 90ms/step - loss: 0.5857 - accuracy: 0.6953 - val_loss: 0.5508 - val_accuracy: 0.7300
Epoch 3/100
100/100 [==============================] - 9s 91ms/step - loss: 0.5793 - accuracy: 0.7025 - val_loss: 0.6336 - val_accuracy: 0.6200
Epoch 4/100
100/100 [==============================] - 9s 90ms/step - loss: 0.5642 - accuracy: 0.7125 - val_loss: 0.5282 - val_accuracy: 0.7450
Epoch 5/100
100/100 [==============================] - 9s 90ms/step - loss: 0.5673 - accuracy: 0.6978 - val_loss: 0.5281 - val_accuracy: 0.7412
Epoch 6/100
100/100 [==============================] - 9s 91ms/step - loss: 0.5477 - accuracy: 0.7222 - val_loss: 0.5521 - val_accuracy: 0.7113
Epoch 7/100
100/100 [==============================] - 9s 92ms/step - loss: 0.5377 - accuracy: 0.7209 - val_loss: 0.5642 - val_accuracy:

100/100 [==============================] - 10s 96ms/step - loss: 0.4604 - accuracy: 0.7844 - val_loss: 0.4783 - val_accuracy: 0.7875
Epoch 58/100
100/100 [==============================] - 10s 97ms/step - loss: 0.4472 - accuracy: 0.7887 - val_loss: 0.4858 - val_accuracy: 0.7763
Epoch 59/100
100/100 [==============================] - 10s 96ms/step - loss: 0.4411 - accuracy: 0.7881 - val_loss: 0.5027 - val_accuracy: 0.7613
Epoch 60/100
100/100 [==============================] - 9s 92ms/step - loss: 0.4410 - accuracy: 0.7997 - val_loss: 0.6275 - val_accuracy: 0.6913
Epoch 61/100
100/100 [==============================] - 10s 96ms/step - loss: 0.4536 - accuracy: 0.7931 - val_loss: 0.4761 - val_accuracy: 0.7788
Epoch 62/100
100/100 [==============================] - 10s 99ms/step - loss: 0.4402 - accuracy: 0.8034 - val_loss: 0.5486 - val_accuracy: 0.7625
Epoch 63/100
100/100 [==============================] - 10s 98ms/step - loss: 0.4495 - accuracy: 0.7912 - val_loss: 0.4897 - val_accuracy:

In [ ]:
import numpy as np

from keras.preprocessing import image

In [11]:
new_image = image.load_img(
    'test_image_2.jpg',
    target_size = (64, 64)
)

In [12]:
new_image = image.img_to_array(new_image)
new_image = np.expand_dims(new_image, axis = 0)

result = classifier.predict(new_image)
#trainSet.class_indices

if result[0][0] == 1:
    prediction = 'Dog'
else:
    prediction = 'Cat'
    
print(prediction)

Cat


In [ ]:
# 라플라스 변환 => 전달 함수를 얻기 위해 계산함
# 입력 대 출력비를 구하겠다.
# 입력이 10, 출력이 7, 입출력비: 7/10 = 0.7
# 입력이 y'' = y' + 3y + 2 
# 출력이 y' = 3e^3x => y = e^3x
# 라플라스 변환 통해 입출력비를 계산할 수 있게 된다.
# intergeral 0 - int f(t)e^-st dt

# 1계 미분 방정식(RC 회로)
# 라플라스 변환, 푸리에 변환 약식
# Low Pass Filter(LPF 설계법) - ID Convolution
# 전달 함수 -> 실제 값을 필터링 하는 방법