In [1]:
print('응')

응


In [2]:
# 베이스 - 디지털 신호 처리
# CNN - FIR 필터(음성 분석)
# RNN, LTSM - IIR 필터(음성 분석)
# 피드백(IIR)을 준다는 개념은
# 특정값을 찾아 수렴시키는 것이라 보면 된다.
# 마이크로 펀딩 => FPGA

In [3]:
# y(u, x) => ∂y / ∂u 혹은 ∂y / ∂x
# y' = ∂y / ∂x * ∂x / ∂u

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
!ls Applied-Deep-Learning-with-Keras/Lesson09

AAPL_test.csv	  Activity18.ipynb  Exercise28.ipynb
AAPL_train.csv	  Activity19.ipynb  MSFT_test.csv
Activity17.ipynb  Exercise27.ipynb  MSFT_train.csv


In [6]:
trainSet = pd.read_csv(
    'Applied-Deep-Learning-with-Keras/Lesson09/AAPL_train.csv'
)
trainSet.head()

Date       Open       High        Low      Close  Adj Close  \
0  02-01-2014  79.382858  79.575714  78.860001  79.018570  66.964325   
1  03-01-2014  78.980003  79.099998  77.204285  77.282860  65.493416   
2  06-01-2014  76.778572  78.114288  76.228569  77.704285  65.850533   
3  07-01-2014  77.760002  77.994286  76.845711  77.148575  65.379593   
4  08-01-2014  76.972855  77.937141  76.955711  77.637146  65.793633   

      Volume  
0   58671200  
1   98116900  
2  103152700  
3   79302300  
4   64632400

In [7]:
trainSetOpen = trainSet.iloc[:, 1:2].values
trainSetOpen

array([[ 79.382858],
       [ 78.980003],
       [ 76.778572],
       ...,
       [155.839996],
       [157.5     ],
       [158.529999]])

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
sc = MinMaxScaler(feature_range = (0, 1))
trainSetScaled = sc.fit_transform(trainSetOpen)
trainSetScaled

array([[0.05400437],
       [0.05148716],
       [0.03773165],
       ...,
       [0.53174205],
       [0.54211448],
       [0.54855037]])

In [10]:
X_train = []
y_train = []

for i in range(60, 1258):
    X_train.append(trainSetScaled[i - 60:i, 0])
    y_train.append(trainSetScaled[i, 0])
    
X_train = np.array(X_train)
y_train = np.array(y_train)

In [11]:
X_train = np.reshape(
    X_train, (X_train.shape[0], X_train.shape[1],1)
)
X_train

array([[[0.05400437],
        [0.05148716],
        [0.03773165],
        ...,
        [0.04582785],
        [0.04002572],
        [0.03850823]],

       [[0.05148716],
        [0.03773165],
        [0.04386406],
        ...,
        [0.04002572],
        [0.03850823],
        [0.03932056]],

       [[0.03773165],
        [0.04386406],
        [0.03894562],
        ...,
        [0.03850823],
        [0.03932056],
        [0.03800839]],

       ...,

       [[0.98231691],
        [0.97794302],
        [0.99543867],
        ...,
        [0.53811549],
        [0.48369155],
        [0.48462887]],

       [[0.97794302],
        [0.99543867],
        [1.        ],
        ...,
        [0.48369155],
        [0.48462887],
        [0.53174205]],

       [[0.99543867],
        [1.        ],
        [0.98237946],
        ...,
        [0.48462887],
        [0.53174205],
        [0.54211448]]])

In [12]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout

Using TensorFlow backend.
/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflo

ImportError: cannot import name 'export_saved_model' from 'tensorflow.python.keras.saving.saved_model' (/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/__init__.py)

In [ ]:
# 교재
#model = Sequential()

#model.add(LSTM(
#    50, return_sequences = True, 
#        input_shape = (X_train.shape[1], 1)
#    )
#)
#model.add(LSTM(50, return_sequences = True))
#model.add(LSTM(50, return_sequences = True))
#model.add(LSTM(50))
#model.add(Dense(1))

In [ ]:
model = Sequential()

model.add(LSTM(
    150, return_sequences = True, 
        input_shape = (X_train.shape[1], 1)
    )
)
model.add(LSTM(150, return_sequences = True))
model.add(LSTM(100, return_sequences = True))
model.add(LSTM(100))
model.add(Dense(1))

In [ ]:
model.compile(
    optimizer = 'adam',
    loss = 'mean_squared_error'
)
model.fit(
    X_train, y_train, epochs = 100, batch_size = 32
)

In [ ]:
testSet = pd.read_csv(
    'Applied-Deep-Learning-with-Keras/Lesson09/AAPL_test.csv'
)
testSet.head()

In [ ]:
actualStock = testSet.iloc[:, 1:2].values
actualStock

In [ ]:
total = pd.concat(
    (trainSet['Open'], testSet['Open']),
    axis = 0
)

In [ ]:
input = total[len(total) - len(testSet) - 60:].values
input = input.reshape(-1, 1)
input = sc.transform(input)

X_test = []

for i in range(60, 81):
    X_test.append(input[i - 60:i, 0])
    
X_test = np.array(X_test)
X_test = np.reshape(
    X_test,
    (X_test.shape[0], X_test.shape[1], 1)
)

predictedStock = model.predict(X_test)
predictedStock = sc.inverse_transform(predictedStock)

In [ ]:
plt.plot(
    actualStock, color = 'green',
    label = 'Real Apple Stock', ls = '--'
)
plt.plot(
    predictedStock, color = 'red',
    label = 'Predicted Apple Stock', ls = '-'
)
plt.title('Predicted Stock Price')
plt.xlabel('Time in days')
plt.ylabel('Real Stock Price')
plt.legend()
plt.show()
# IIR 필터의 특성이 나타나고 있음
# 위상이 뒤틀린다.

In [ ]:
# 1. 새로운 터미널을 킨다.
# 2. pip uninstall -y keras
# 3. pip uninstall -y tensorflow
# 4. pip uninstall -y tensorflow-gpu
# 5. rm -rf ~/.keras
# 6. 새로 킨 터미널을 껏다가 다시 킨다.
# 7. pip install tensorflow==1.14
# 8. pip install keras==2.2.5
# 9. 터미널을 다시 껏다가 킨다.
# 10. jupyter notebook을 구동시킨다.

In [1]:
from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import preprocess_input
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image

import numpy as np

Using TensorFlow backend.
/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/bitai/anaconda3/lib/python3.7/site-packages/tensorflo

In [2]:
def prepare_img(img, target):
    img = img.resize(target)
    img = img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    img = imagenet_utils.preprocess_input(img)
    
    return img

In [3]:
resModel = None

def load_model():
    global resModel
    resModel = ResNet50()

In [4]:
import keras.backend.tensorflow_backend as tb
import tensorflow as tf

global graph, model
graph = tf.get_default_graph()

print(tf.__version__)

1.14.0


In [5]:
from flask import Flask, request, jsonify
from werkzeug.utils import secure_filename

In [ ]:
app = Flask(__name__)

@app.route('/imgServer', methods = ['GET', 'POST'])
def analysis_img():
    data = {"success": False}
    if request.method == 'POST':
        print('POST')
        file = request.files['file']
        file = secure_filename(file.filename)
        print(file)
        
        sea_img = image.load_img(
            file, target_size = (224, 224)
        )
        
        trans_img = image.img_to_array(sea_img)
        trans_img = np.expand_dims(trans_img, axis = 0)
        trans_img = preprocess_input(trans_img)
        print(trans_img.shape)
        
        with graph.as_default():
            pred = resModel.predict(trans_img)
            
        label = decode_predictions(pred)
        data["predictions"] = []
        
        for (imageNetID, label, prob) in label[0]:
            r = {
                "label": label, 
                "probability": float(prob)
            }
            data["predictions"].append(r)
            
        data["success"] = True
        
    return jsonify(data)

if __name__ == "__main__":
    load_model()
    app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Jul/2020 15:10:42] "POST /imgSever HTTP/1.1" 404 -
127.0.0.1 - - [20/Jul/2020 15:10:48] "POST /imgSever HTTP/1.1" 404 -
127.0.0.1 - - [20/Jul/2020 15:13:46] "POST /imgSever HTTP/1.1" 404 -
127.0.0.1 - - [20/Jul/2020 15:13:49] "GET /imgServer HTTP/1.1" 200 -
[2020-07-20 15:13:57,986] ERROR in app: Exception on /imgServer [POST]
Traceback (most recent call last):
  File "/home/bitai/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bitai/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bitai/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bitai/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/ho

POST

POST
test_image_2.jpg
(1, 224, 224, 3)


127.0.0.1 - - [20/Jul/2020 15:14:08] "POST /imgServer HTTP/1.1" 200 -
